#Apache install
- hosts: vagrants
  sudo: yes
#  become: yes
#  become_user: vagrant
 
  tasks:
    - name: yum install epel-repease
      yum: name=epel-release state=installed

    - name: add remi-repo repository
      command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo
  
    - name: install php 7.2
      yum: name={{ item }} enablerepo=remi,remi-php72 state=installed
      with_items:
        - php
        - php-intl
        - php-cli
        - php-common
        - php-dbg
        - php-devel
        - php-gd
        - php-mbstring
        - php-mcrypt
        - php-mysqlnd
        - php-pdo
        - php-xml
        - php-zip


